
package gui;

import java.awt.Color;
import app.Main;
import introduction.ComplexNumber;
/**
 *
 * @author xeon
 */
public class Introduction extends javax.swing.JFrame {
    Main main;
    /**
     * Creates new form ComplexNumberASYS
     */
    public Introduction(Main main) {
        initComponents();
        
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComplexNumbers = new javax.swing.JPanel();
        lblHOME = new javax.swing.JLabel();
        lblComplexNumbers = new javax.swing.JLabel();
        lblLogoComplexNumbers = new javax.swing.JLabel();
        lblTema1 = new javax.swing.JLabel();
        lblIndicacion = new javax.swing.JLabel();
        lblReal = new javax.swing.JLabel();
        lbImag = new javax.swing.JLabel();
        lblZ1 = new javax.swing.JLabel();
        tfZ1Real = new javax.swing.JTextField();
        tfZ1Imag = new javax.swing.JTextField();
        lblZ2 = new javax.swing.JLabel();
        tfZ2Real = new javax.swing.JTextField();
        tfZ2Imag = new javax.swing.JTextField();
        btnCompute = new javax.swing.JButton();
        lblAdd = new javax.swing.JLabel();
        lblSubs = new javax.swing.JLabel();
        lblMult = new javax.swing.JLabel();
        lblDiv = new javax.swing.JLabel();
        lblModZ1 = new javax.swing.JLabel();
        lblArgZ1 = new javax.swing.JLabel();
        lblFoot = new javax.swing.JLabel();
        lblFoot1 = new javax.swing.JLabel();
        lblZ1AddZ2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlComplexNumbers.setBackground(new java.awt.Color(0, 0, 0));
        pnlComplexNumbers.setPreferredSize(new java.awt.Dimension(800, 500));
        pnlComplexNumbers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHOME.setBackground(new java.awt.Color(0, 0, 0));
        lblHOME.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblHOME.setForeground(new java.awt.Color(255, 78, 0));
        lblHOME.setText("Inicio");
        lblHOME.setOpaque(true);
        lblHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHOMEMouseExited(evt);
            }
        });
        pnlComplexNumbers.add(lblHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 70, 50));

        lblComplexNumbers.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblComplexNumbers.setForeground(new java.awt.Color(255, 78, 0));
        lblComplexNumbers.setText("Números complejos");
        pnlComplexNumbers.add(lblComplexNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 430, 50));

        lblLogoComplexNumbers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tema1_NumerosComplejos-small.png"))); // NOI18N
        lblLogoComplexNumbers.setText("jLabel1");
        pnlComplexNumbers.add(lblLogoComplexNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 120));

        lblTema1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTema1.setForeground(new java.awt.Color(255, 255, 255));
        lblTema1.setText("Tema 1. Introducción. Operaciones básicas con números complejos.");
        pnlComplexNumbers.add(lblTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 560, 30));

        lblIndicacion.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblIndicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblIndicacion.setText("Indicaciones: introduzca dos números complejos para calular las operaciones indicadas.");
        pnlComplexNumbers.add(lblIndicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 550, 20));

        lblReal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReal.setForeground(new java.awt.Color(255, 255, 255));
        lblReal.setText("Real");
        pnlComplexNumbers.add(lblReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        lbImag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbImag.setForeground(new java.awt.Color(255, 255, 255));
        lbImag.setText("Imag");
        pnlComplexNumbers.add(lbImag, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        lblZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblZ1.setText("Número complejo Z1: ");
        pnlComplexNumbers.add(lblZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        tfZ1Real.setText("1.0");
        tfZ1Real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ1RealActionPerformed(evt);
            }
        });
        pnlComplexNumbers.add(tfZ1Real, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, -1));

        tfZ1Imag.setText("1.0");
        pnlComplexNumbers.add(tfZ1Imag, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 50, -1));

        lblZ2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblZ2.setForeground(new java.awt.Color(255, 255, 255));
        lblZ2.setText("Número complejo Z2: ");
        pnlComplexNumbers.add(lblZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        tfZ2Real.setText("1.0");
        tfZ2Real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ2RealActionPerformed(evt);
            }
        });
        pnlComplexNumbers.add(tfZ2Real, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, -1));

        tfZ2Imag.setText("1.0");
        tfZ2Imag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ2ImagActionPerformed(evt);
            }
        });
        pnlComplexNumbers.add(tfZ2Imag, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 50, -1));

        btnCompute.setText("Compute");
        btnCompute.setBorder(null);
        btnCompute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComputeMouseClicked(evt);
            }
        });
        pnlComplexNumbers.add(btnCompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 20));

        lblAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("Z1 + Z2: ");
        pnlComplexNumbers.add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lblSubs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSubs.setForeground(new java.awt.Color(255, 255, 255));
        lblSubs.setText("Z1   - Z2: ");
        pnlComplexNumbers.add(lblSubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        lblMult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMult.setForeground(new java.awt.Color(255, 255, 255));
        lblMult.setText("Z1  *  Z2: ");
        pnlComplexNumbers.add(lblMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        lblDiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDiv.setForeground(new java.awt.Color(255, 255, 255));
        lblDiv.setText("Z1  /  Z2:");
        pnlComplexNumbers.add(lblDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        lblModZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblModZ1.setText("     | Z1 |:");
        pnlComplexNumbers.add(lblModZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        lblArgZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArgZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblArgZ1.setText("Arg(Z1):");
        pnlComplexNumbers.add(lblArgZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        lblFoot.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot.setText("Francisco Javier Montecillo Puente");
        pnlComplexNumbers.add(lblFoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        lblFoot1.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot1.setText("ITESS-TICS-2023 Ago-Dic");
        pnlComplexNumbers.add(lblFoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        lblZ1AddZ2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblZ1AddZ2.setForeground(new java.awt.Color(255, 0, 0));
        lblZ1AddZ2.setText("Pending");
        pnlComplexNumbers.add(lblZ1AddZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComplexNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComplexNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseEntered
        // TODO add your handling code here:
        lblHOME.setBackground(Color.yellow);
    }//GEN-LAST:event_lblHOMEMouseEntered

    private void lblHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseExited
        // TODO add your handling code here:
        lblHOME.setBackground(Color.black);
    }//GEN-LAST:event_lblHOMEMouseExited

    private void lblHOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseClicked
       // TODO add your handling code here:
       main.introduction.setVisible(false);
       main.introduction = null;
       
       main.mainASYS.setVisible(true);
    }//GEN-LAST:event_lblHOMEMouseClicked

    private void tfZ1RealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ1RealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ1RealActionPerformed

    private void tfZ2ImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ2ImagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ2ImagActionPerformed

    private void tfZ2RealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ2RealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ2RealActionPerformed

    private void btnComputeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputeMouseClicked
        // TODO add your handling code here:
        String z1real = tfZ1Real.getText();
        String z1imag = tfZ1Imag.getText();
        
        String z2real = tfZ2Real.getText();
        String z2imag = tfZ2Imag.getText();
        
        ComplexNumber z1 = new ComplexNumber(
                Float.parseFloat(z1real),
                Float.parseFloat(z1imag));
        ComplexNumber z2 = new ComplexNumber(
                Float.parseFloat(z2real),
                Float.parseFloat(z2imag));
        
        ComplexNumber rz = z1.add(z2);
        
        lblZ1AddZ2.setText(rz.toString());
    }//GEN-LAST:event_btnComputeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ComplexNumbersASYS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.JLabel lbImag;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblArgZ1;
    private javax.swing.JLabel lblComplexNumbers;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblFoot1;
    private javax.swing.JLabel lblHOME;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblLogoComplexNumbers;
    private javax.swing.JLabel lblModZ1;
    private javax.swing.JLabel lblMult;
    private javax.swing.JLabel lblReal;
    private javax.swing.JLabel lblSubs;
    private javax.swing.JLabel lblTema1;
    private javax.swing.JLabel lblZ1;
    private javax.swing.JLabel lblZ1AddZ2;
    private javax.swing.JLabel lblZ2;
    private javax.swing.JPanel pnlComplexNumbers;
    private javax.swing.JTextField tfZ1Imag;
    private javax.swing.JTextField tfZ1Real;
    private javax.swing.JTextField tfZ2Imag;
    private javax.swing.JTextField tfZ2Real;
    // End of variables declaration//GEN-END:variables
}
